### ISSUE TITLE
Right-Click Menu

### ISSUE THREAD

**Issue by neoOpus** [dessant/search-by-image#144]
**System**

* OS name: Windows
* OS version: 11
* Browser name: Edge (chromium)
* Browser version: 94.0.992.50
* Extension version: 4.0.0

**Bug description**

**Comment by mpql** [comment]
Hi, I am also getting this issue from time to time, but it's not caused by a particular page, and I cannot reproduce it consistently. Once it's happening, though, it will repeat a lot, if not every time. Then I can simply use the menu option once, and it'll be missing from the same image's context menu in the same browser tab (and other tabs -- possibly ones running in the same browser process?).

I tried disabling and re-enabling the plugin, and now I cannot get it to happen again. So maybe that is a tentative workaround for anyone else finding this issue in the future.

Screenshots:

![image](https://user-images.githubusercontent.com/1709954/141610629-c2435a4b-1233-4167-aa38-caf1a80553d5.png)

![image](https://user-images.githubusercontent.com/1709954/141610783-b274af5f-17fd-4bb7-99ac-1fe17c8be71a.png)

**Comment by dessant** [comment]
Hi @mpql, which browser are you using?

**Comment by bill-system76** [comment]
Hey @dessant ; I was able to replicate this issue in both Brave (my everyday browser), and Chrome.

**Comment by mpql** [comment]
Hey @dessant ; I was able to replicate this issue in both Brave (my everyday browser), and Chrome.

**Comment by neoOpus** [comment]
Just as mpql described it is reproducible, but it isn't specific to a website or setting... it can be fixed momentarily by changing the settings back and forth... but it is persistently plaguing the extension and the only reliable option is the icon menu, but the right click is much better in terms of usability... I am using Edge (chromium) the latest version and I don't think it is due to a conflict with other extension or userscript... I will try to provide you with additional information, but if you want to access to my machine remotely, then we can manage to do this.

**Comment by dessant** [comment]
I could not reproduce it, but there was an issue that may have caused the bug, the context menu was recreated whenever the storage has changed, this was fixed in https://github.com/dessant/search-by-image/commit/777fe063d7b76c26526ce75100a639df19854196.

Version 4.3.1 and newer will contain the fix, please let me know if the bug is still present after the update.

**Comment by neoOpus** [comment]
My actual solution is to go to Options then disable the context menu and re-enable it… it works then after I refresh the page and remain but it is hard to tell why it stops working… I will see if the update fixes it! Thank you dessant for your tremendous work!

**Comment by dessant** [comment]
@neoOpus, @mpql, have you seen the bug since updating to 4.3.1? A new bug report claims that the issue is still present: https://github.com/dessant/search-by-image/issues/151

**Comment by neoOpus** [comment]
> 

Yes it is still happening, and the solution is the same disable/enable the menu from settings, if possible it would be better to access that from right-clicking the icon or the popup menu.

**Comment by dessant** [comment]
Btw, have you been using an InPrivate window in Edge, the issue so far seems to be a Chromium bug, also reproducible when an Incognito window is opened: https://github.com/dessant/search-by-image/issues/151#issuecomment-986086489

**Comment by mpql** [comment]
> @neoOpus, @mpql, have you seen the bug since updating to 4.3.1? A new bug report claims that the issue is still present: #151

I have not seen it repeat, but take that with a grain of salt -- it's been sporadic. I will report back if I see it again. :)

**Comment by neoOpus** [comment]
> Btw, have you been using an InPrivate window in Edge, the issue so far seems to be a Chromium bug, also reproducible when an Incognito window is opened: [#151 (comment)](https://github.com/dessant/search-by-image/issues/151#issuecomment-986086489)

Yes I just read that, I am about to try disabling the incognito permission and see how things works, I really appreciate how he investigated the issue and provided a solution.

BTW I confirm that on Firefox it works flawlessly so it is certainly a Chromium issue

**Comment by dessant** [comment]
@mpql, if the issue appears when an Incognito window is opened, that was fixed in 4.4.1, details here https://github.com/dessant/search-by-image/issues/151#issuecomment-993623854. Please let me know if you weren't using an Incognito window.

Version 4.4.1 has been submitted to CWS yesterday, so it will probably be reviewed and published in a couple of days.

**Comment by mpql** [comment]
Good to know. No, it was not an incognito window. Ironically, it was a standard window, and my method of working around this was to copy the URL, open an Incognito window, and use the context menu there. Sorry I don't have better news. That said, it's possible it was related somehow; if I see it again on 4.4.1, I will report back. :)

And thanks for your work!

**Comment by neoOpus** [comment]
> Good to know. No, it was not an incognito window. Ironically, it was a standard window, and my method of working around this was to copy the URL, open an Incognito window, and use the context menu there. Sorry I don't have better news. That said, it's possible it was related somehow; if I see it again on 4.4.1, I will report back. :)
> 
> And thanks for your work!

You didn't get it

**Comment by neoOpus** [comment]
Now it works flawlessly! I didn't have the issue at all today! so I can consider it fixed hopefully

**Comment by mpql** [comment]
> You didn't get it

What?
